### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by strawberry-choco**
Updated rss and atom dependencies.

### CODE REVIEW

**Comment by apiraino** [comment]
+1 for this PR (if no blockers).

I'd like to use the latest version of the underlying RSS crate.

@frewsxcv r? anyone?

**Comment by strawberry-choco** [comment]
Updated the rss crate to its latest version. Now it is all up to the maintainers.

**Review by frewsxcv — APPROVED** [review]
Thanks for being patient and thanks for your contribution! 🙇

**Comment by frewsxcv** [comment]
@tomshen Can you add either me or the rust-syndication GitHub org as an owner of this repo? I'm not an owner so I'm unable to publish this change. Thanks!

**Comment by tomshen** [comment]
@frewsxcv Weirdly, I also don’t seem to have owner permissions on this repo (no settings tab visible on this repo).

**Comment by frewsxcv** [comment]
@tomshen Ah sorry, I misspoke. You're the sole owner of the crate host on crates.io: https://crates.io/crates/syndication

**Comment by tomshen** [comment]
Ah okay, that makes more sense. Invite sent!

**Comment by frewsxcv** [comment]
Thanks!

**Comment by frewsxcv** [comment]
Hmm, I didn't get an invite, can you double check when you get a chance?

**Comment by tomshen** [comment]
Have you logged into crates.io with your github account before? I tried adding your github username again (frewsxcv) just now.

**Comment by frewsxcv** [comment]
Ah yep I see the invite, thanks! I'll publish a new version later when I'm at my computer

**Comment by frewsxcv** [comment]
Sorry for the delay! I just published a new version

**Pull request merged**
